### ISSUE TITLE
breaking change in 1.2.0

### ISSUE THREAD

**Issue by targos** [koajs/cors#15]
In https://github.com/koajs/cors/commit/677833d31606dc261f33092054bdf66ba9e586cf an unconditional `yield next;` has been added at the end of the middleware. It is breaking preflight requests on our servers because in earlier versions the middleware chain stopped at `this.status = 204`.

**Comment by maximusmusterus1** [comment]
I've experienced the same problem and downgraded to 1.1.0 for the moment. What is the intended way to solve this? In my opinion kcors should handle the preflight request by itself. Otherwise I would need to add another middleware to 'close' options-requests before they will be responded with 404.

**Comment by dead-horse** [comment]
sorry, it will fixed in https://github.com/koajs/cors/pull/16

**Comment by targos** [comment]
Thanks!

**Comment by maximusmusterus1** [comment]
Thank you, good job!
