### ISSUE TITLE
Not setting headers on Koa2 / Node 6.2

### ISSUE THREAD

**Issue by KingScooty** [koajs/cors#18]
The headers don't seem to be getting set on the latest version of Koa 2 with node 6.2. Any ideas?

**Comment by tsvetann** [comment]
same issue here

**Comment by dead-horse** [comment]
can you give a simple code(server and client) to reproduce the issue?

**Comment by tsvetann** [comment]
Using koa2!

On server:
```
const cors = require('kcors')
app.use(convert(cors()))
```

On Client (origin different than server):
make ajax request with content-type: 'application/json'

**Comment by jakewmeyer** [comment]
This is still an issue, still waiting on the PR to be merged

**Comment by garretttaco** [comment]
Still seeing this as an issue as well. The PR above does not seem to fix it, however. As referenced in the PR, it is setting the allowed origin to the origin of the responding server.

**Comment by nhhockeyplayer** [comment]
maybe we are using the wrong library

**Comment by CleberRossi** [comment]
> This is still an issue, still waiting on the PR to be merged

I just opened a PR. Hope it is still in time :)
