### ISSUE TITLE
ctx.throw || ctx.assert doesn't send the headers back

### ISSUE THREAD

**Issue by Nighthawk14** [koajs/cors#21]
When using `ctx.throw` or `ctx.assert` the cors headers are not sent back. Maybe I'm using it wrong but any help would be welcome :).

example:
```js
router.post('/', (ctx) => {
  let {name, jurisdiction, parentTitle} = ctx.request.body;
  const project = ctx.request.body;

  ctx.assert(name && jurisdiction && parentTitle, 400);
```

Thanks!

**Comment by dead-horse** [comment]
what version of koa and kcors are you using?

**Comment by Nighthawk14** [comment]
koa@2.0.0-alpha.3 and kcors@2.1.1 :)

**Comment by dead-horse** [comment]
if you are using default error handler in koa, please update your koa to 2.0.0-beta.4

**Comment by Nighthawk14** [comment]
@dead-horse Thanks for the help, it's definitely better! 😃
