### ISSUE TITLE
add PATCH to default methods

### ISSUE THREAD

**Issue by defunctzombie** [koajs/cors#22]
What is the reason it is not part of the default methods?

**Comment by dougwilson** [comment]
>What is the reason it is not part of the default methods?

I don't think there is any reason why it is not. I looked around and these default methods seem to be the common ones from different cors modules (even across different code languages).

**Comment by defunctzombie** [comment]
@dougwilson accept a PR to add it or want to leave as is?

**Comment by dougwilson** [comment]
> accept a PR to add it or want to leave as is?

I would leave it up to whatever @fengmk2 wants to do :)

**Comment by fengmk2** [comment]
PR please @defunctzombie

**Comment by defunctzombie** [comment]
See https://github.com/koajs/cors/pull/23

**Comment by fengmk2** [comment]
Latest two versions has fixed this.

```bash
npm dist-tag ls
latest: 1.3.0
next: 2.2.0
```
