### ISSUE TITLE
warning using koa@next

### ISSUE THREAD

**Issue by chovy** [koajs/cors#29]
```
Mon, 26 Dec 2016 18:51:50 GMT koa deprecated Support for generators will been removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/tree/v2.x#old-signature-middleware-v1x at src/app.js:18:4
```

**Comment by scttcper** [comment]
Make sure you're using kcors@2

https://github.com/koajs/cors/tree/v2.x

**Comment by chovy** [comment]
How do I install v2 from npm? I tried `npm install kcors@next` is that wrong?

**Comment by scttcper** [comment]
i have `"kcors": "^2.2.0"` in my package.json

**Comment by GuillaumeLeclerc** [comment]
I think it should be the default now since the koa version changed

**Comment by fengmk2** [comment]
close by https://github.com/koajs/cors/pull/51
