### ISSUE TITLE
Tag version 2.2.1 as `latest`

### ISSUE THREAD

**Issue by natesilva** [koajs/cors#33]
Koa 2 is released. 🎉

**Comment by jaydenseric** [comment]
This should be easy to action, is there something in the way?

This is a gotcha for people trying to install it for the current version on Koa, and causes confusion when using `npm outdated`:

<img width="406" alt="screen shot 2017-06-02 at 4 13 16 pm" src="https://cloud.githubusercontent.com/assets/1754873/26713204/af961ac0-47ae-11e7-9d9b-13c5d28a5e3d.png">

**Comment by fengmk2** [comment]
Done!

```
npm dist-tag ls kcors
latest: 2.2.1
next: 2.2.1
```
