### ISSUE TITLE
republish as @koa/cors?

### ISSUE THREAD

**Issue by jonathanong** [koajs/cors#35]
might be better than kcors, especially since there's a `koa-cors` that is no longer maintained

**Comment by ianstormtaylor** [comment]
Or even get the `koa-cors` maintainer to give up the name ideally.

But yeah, +1 because `kcors` is hard to remember when I'm looking through dependencies what it is...

**Comment by fengmk2** [comment]
I'm ok for this. @jonathanong just do it and add a deprecated message on the `kcors` package.

**Comment by jonathanong** [comment]
done

**Comment by jonathanong** [comment]
i do not have access to kcors

**Comment by stevehipwell** [comment]
I'm not sure that `@koa/cors` is the best name for this package as it's not consistent with the other core `koa` packages. Ideally you could get the `koa-cors` package name, otherwise maybe something more like `koa-cors-official`.

**Comment by jonathanong** [comment]
@stevehipwell we can slowly move koa packages to `@koa/*`

**Comment by stevehipwell** [comment]
@jonathanong - If this is the policy for all koa packages then it makes sense, however you might want to notify the relevant TypeScript definition authors that the package has moved as `@koa/cors` doesn't have any definitions but `kcors` does.

**Comment by VladShcherbin** [comment]
The name without `@` is better because now it differs from the rest of `koa` family and is the first one in dependency list, even above packages that start with `a` letter.

Will stick with `kcors` for now.

**Comment by raphaelsoul** [comment]
currently I copy declare code from `@types/koa2-cors` to my `index.d.ts`

```
declare module "@koa/cors" {
    import * as Koa from 'koa';
    namespace cors {
        interface Options {
            origin?: string | ((ctx: Koa.Context) => boolean | string);
            exposeHeaders?: string[];
            maxAge?: number;
            credentials?: boolean;
            allowMethods?: string[];
            allowHeaders?: string[];
        }
    }

    function cors(options?: cors.Options): Koa.Middleware;

    export = cors;
}
```

**Comment by fengmk2** [comment]
done https://www.npmjs.com/package/@koa/cors
