### ISSUE TITLE
Incorrect version tagged as latest

### ISSUE THREAD

**Issue by jaydenseric** [koajs/cors#38]
This morning I ran `npm outdated` this morning and noticed something funny with `kcors`:

<img width="245" alt="screen shot 2017-09-14 at 12 27 24 pm" src="https://user-images.githubusercontent.com/1754873/30409418-34e66dfc-9948-11e7-98a0-9cc8ce28d67f.png">

An older version has been published as `@latest` on npm:

<img width="455" alt="screen shot 2017-09-14 at 12 25 41 pm" src="https://user-images.githubusercontent.com/1754873/30409383-0aed3be8-9948-11e7-97ba-8f944b078769.png">

**Comment by fengmk2** [comment]
I forget to change the latest tag, fixed now.

```
npm dist-tag ls kcors
latest: 2.2.1
next: 2.2.1
```
