### ISSUE TITLE
should CORS be abandoned?

### ISSUE THREAD

**Issue by jackzhp** [koajs/cors#40]
I think that CORS design is completely unnecessary, and so should be abandoned. I have laid down my arguments, if you think you know this issue pretty well, would you please look at it, and comment it.

https://github.com/jackzhp/CORS-should-retire
or
http://blog.sina.com.cn/s/blog_93b70ae70102wxe8.html

**Comment by fengmk2** [comment]
I still using CORS today, and can't see it will be abandoned in future.
