### ISSUE TITLE
why set status of `options` for Preflight Request 204

### ISSUE THREAD

**Issue by NoraGithub** [koajs/cors#41]
I read the code and felt puzzle about setting the status 204 forever for the result of `options`request for Preflight Request. I thought it should be controlled by other components like a real backend( my one is django)

It would be greate if you can reply to give a hand. 👍

**Comment by NoraGithub** [comment]
My faults. The order makes sense.
```
app.use(router.routes());
app.use(cors({'Access-Control-Allow-Origin':target_url}));
```
fixed it.

**Comment by NoraGithub** [comment]
Still unsolved

**Comment by rapzo** [comment]
I may be wrong but it is to avoid sendind (or calculating) Content-length. Since OPTIONS has no content, 204 seems appropriate.

**Comment by NoraGithub** [comment]
Yes, you are right.
 I search for some docs and sometimes it's  said to be 200 and sometimes it's said to be 204, and 204 looks like the right answer according to the semantic. What I ought to doubt should be why my backend(DRF) return 200. 
And one more issue, if some developers want to do something custom on the status code, it would fail. This situation is quite seldom , and I close it.


Thanks for your great job.
