### ISSUE TITLE
error: uncaughtException: Cannot find module '@koa/cors'

### ISSUE THREAD

**Issue by nitrocode** [koajs/cors#46]
node throws this exception

    error: uncaughtException: Cannot find module '@koa/cors' date=Mon Nov 20 2017 08:02:33

when requiring this module

    const cors = require('@koa/cors');

Is this module still updated?

**Comment by rapzo** [comment]
I think that @koa never got done. There's an open issue #35

But yeah, it has been silent for a while...

**Comment by mkozjak** [comment]
Works for me on a mac, but doesn't on Raspbian.

**Comment by krini** [comment]
It also works for me on a mac.

**Comment by fengmk2** [comment]
Already published https://www.npmjs.com/package/@koa/cors
