### ISSUE TITLE
Is KoaJS team still there to maintain the project?

### ISSUE THREAD

**Issue by rap2hpoutre** [koajs/cors#50]

**Comment by fengmk2** [comment]
Yes, what's the problem here?

**Comment by rap2hpoutre** [comment]
Oops sorry about that. It was just a test.

I asked because I was reading the issue and some where opened in 2017 without response (_I'm not blaming_), then I asked myself "is the koa community still alive?" (because I'm starting a project with Koa and saw some half-dead libs -- still I'm almost new in the backend JS ecosystem). SO I tried with a small message on an "official" library, just to check the health. Thank you!

_I don't wanted to be rude, I hope it's OK._

Still, I think you could close this one: https://github.com/koajs/cors/issues/40
